instruction: "Ini adalah soal berbentuk pilihan ganda. Pilihlah salah satu jawaban yang dianggap benar dengan memberikan huruf yang sesuai dengan jawaban!"
prompt: "\n[INPUT]\n[OPTION]\n\nJawaban: "
type_options: "dynamic_choice"
options:
  - "A"
  - "B"
  - "C"
  - "D"
  - "E"
data_path: "./data/indoMMLU-Processed.csv"
label_column: "[LABEL]"
num_shot: 0